name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'      

      - name: Decode Keystore
        run: |
          echo  "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/release-key.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=release-key.jks" >> android/key.properties
          
      - run: flutter pub get

      - run: flutter build appbundle --release

      - uses: actions/upload-artifact@v4
        with:
          name: signed-aab
          path: build/app/outputs/bundle/release/app-release.aab
          retention-days: 14

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: android

      - name: Decode Play Store service account key
        run: |
          echo "${{ secrets.PLAY_STORE_JSON_KEY }}" | base64 --decode > android/play-store-key.json

      - name: Upload to Play Store internal track
        working-directory: android
        env:
          PLAY_STORE_JSON_KEY_PATH: play-store-key.json
        run: bundle exec fastlane internal

